# Generated by Django 4.2.5 on 2023-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(default='default_image.jpg', upload_to='recipe'),
        ),
    ]
